spring.application.name=teller-bank

# Konfigurasi Database (Menggunakan Environment Variables untuk Cloud)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Mengubah path default Swagger (opsional)
springdoc.swagger-ui.path=/swagger-ui.html

# Pengurutan endpoint agar rapi (berdasarkan method: GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=method