spring.application.name=teller-bank

# Konfigurasi Database (Otomatis mendeteksi Cloud atau Local)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/teller}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update

# Mengubah path default Swagger (opsional)
springdoc.swagger-ui.path=/swagger-ui.html

# Pengurutan endpoint agar rapi (berdasarkan method: GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=method